dependencies {
    modImplementation(libs.balmFabric) {
        changing = libs.versions.balm.get().contains("SNAPSHOT")
    }
    modImplementation(libs.kumaFabric)

    // todo: move this to gradle/libs.versions.toml
    modImplementation(include("net.createmod.ponder:Ponder-Fabric-${libs.versions.minecraft.get()}:${libs.versions.ponder.get()}"))
    runtimeOnly("dev.engine-room.flywheel:flywheel-fabric-${libs.versions.minecraft.get()}:${libs.versions.flywheel.get()}")
}
