dependencies {
    modImplementation(libs.balmFabric) {
        changing = libs.versions.balm.get().contains("SNAPSHOT")
    }
    modImplementation(libs.kumaFabric)

    // these are include so this mod can be used without create
    modImplementation(libs.ponderFabric)
    include(libs.ponderFabric)

    runtimeOnly(libs.flywheelFabric)
}
