dependencies {
    implementation(libs.balmNeoForge) {
        changing = libs.versions.balm.get().contains("SNAPSHOT")
    }
    implementation(libs.kumaNeoForge)

    // these are jarjar so this mod can be used without create
    implementation(libs.ponderNeoForge)
    jarJar(libs.ponderNeoForge)

    runtimeOnly(libs.flywheelNeoForge)
    jarJar(libs.flywheelNeoForge)
}
